/*
 * XenForo gallery_bb_code.min.js
 * Copyright 2010-2016 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
(function(b,h,g){XenForo.XenGalleryButtons=function(a){this.__construct(a)};XenForo.XenGalleryButtons.prototype={__construct:function(a){this.textarea=a;b(g).bind({EditorInit:b.context(this,"editorInitFunc")})},editorInitFunc:function(a,c){if(c.$textarea[0]==this.textarea[0]&&c.editor.options.enableXmgButton&&c.config.buttonsCustom.custom_gallery)c.config.buttonsCustom.custom_gallery.callback=b.context(this,"galleryButtonCallback")},galleryButtonCallback:function(a){var c=this.ed=a,e=c.$box.find(".xengallery_browser"),
d=this,a=c.$box.find(".redactor_smilies"),c=c.$box.find(".redactor_btn_smilies");a.hide();c.bind({click:function(){e.hide()}});if(e.length)e.slideToggle();else if(!d.loadPending)d.loadPending=!0,XenForo.ajax("index.php?xengallery/editor-browser","",b.context(this,"loadSuccess")).complete(function(){b(".mediaTabContent").show();d.loadPending=!1})},loadSuccess:function(a){XenForo.hasResponseError(a)||a.templateHtml&&new XenForo.ExtLoader(a,b.context(this,"createBrowser"))},createBrowser:function(a){var c=
this.ed,a=b('<div class="xengallery_browser" />').html(a.templateHtml);a.hide();a.on("click",".Thumb",function(a){a.preventDefault();a=b(this);a="[GALLERY="+a.data("type")+", "+a.data("id")+"]"+XenForo.htmlspecialchars(a.data("title"))+"[/GALLERY]";c.execCommand("inserthtml",a);c.focus()});c.$box.append(a);a.xfActivate();a.slideToggle();this.browser=a.find(".browserSection");this.browser.bind({scroll:b.context(this,"beginScroll")})},beginScroll:function(){var a=this.browser;if(a.find(".IsLastPage").length)return!1;
var c=a.scrollTop()+a.outerHeight(),e=a.get(0).scrollHeight,d=this;if(c==e&&!this.loadPending)this.loadPending=!0,a=a.find(".PageNumber:last"),XenForo.ajax("index.php?xengallery/editor-browser",{last_page:a.val()},b.context(this,"loadMoreSuccess")).complete(function(){b(".mediaTabContent").show();d.loadPending=!1})},loadMoreSuccess:function(a){XenForo.hasResponseError(a)||a.templateHtml&&new XenForo.ExtLoader(a,b.context(this,"updateBrowser"))},updateBrowser:function(a){this.browser.find(".gridSection").append(a.templateHtml).xfShow()}};
XenForo.XenGalleryLazyLoader=function(a){this.__construct(a)};XenForo.XenGalleryLazyLoader.prototype={__construct:function(a){this.ignoreActivate=!1;a.bind({XenForoActivate:b.context(this,"elementActivate")});this.checkForItems()},checkForItems:function(){this.timer&&clearTimeout(this.timer);var a=[],c=b(".GalleryLazyLoad");b.each(c,function(c,d){a.push({type:b(d).data("type"),id:b(d).data("id")})});if(!a.length)return!1;this.loadGalleryItems(a,c)},elementActivate:function(){if(!this.ignoreActivate)this.timer&&
clearTimeout(this.timer),this.timer=setTimeout(b.context(this,"checkForItems"),50)},loadGalleryItems:function(a,c){this.xhr=XenForo.ajax("index.php?xengallery/content-loader",{items:a},b.context(this,"ajaxSuccess"));this.xhr.complete(function(){c&&c.removeClass("GalleryLazyLoad")})},ajaxSuccess:function(a){if(XenForo.hasResponseError(a))return!1;a.gallery&&new XenForo.ExtLoader(a,function(){this.ignoreActivate=!0;b.each(a.gallery,function(a,e){var d=a.split("/").pop(),f=b(d+":first");f.removeClass("GalleryLazyLoad");
b(e.html).xfInsert("replaceAll",f,"xfFadeIn",XenForo.speed.normal,function(){b(this).trigger("elementResized")});b(d+"ContentLink").attr("href",e.contentLink)});this.ignoreActivate=!1})}};XenForo.register("textarea.BbCodeWysiwygEditor","XenForo.XenGalleryButtons");XenForo.register(".GalleryLazyLoader","XenForo.XenGalleryLazyLoader")})(jQuery,this,document);
