/*
 * XenForo media_user_tag.min.js
 * Copyright 2010-2016 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
(function(a,f,n){XenForo.XenGalleryImageData=function(a){this.__construct(a)};XenForo.XenGalleryImageData.prototype={__construct:function(h){this.image=h;var d=this;a(n).ready(function(){setTimeout(function(){d.updateMultiplier()},1500)});a(f).bind({resize:a.context(this,"updateMultiplier")});this.cropButton=a(".CropActivate");this.cropButton.bind({click:a.context(this,"updateMultiplier")});this.tagButton=a(".TagActivate");this.tagButton.bind({click:a.context(this,"updateMultiplier")});this.showTagLink=
a(".ShowTags");this.showTagLink.bind({click:a.context(this,"showTags")});a("#mediaTaggedUsers li .TaggedUser").hover(function(){a(".mediaContainer").find(".tagBox."+a(this).attr("id")).addClass("hover");a(".mediaContainer").find(".tagBox."+a(this).attr("id")).xfFadeIn(XenForo.speed.fast).addClass("selected")},function(){a(".mediaContainer").find(".tagBox."+a(this).attr("id")).removeClass("hover");a(".mediaContainer").find(".tagBox."+a(this).attr("id")).xfFadeOut(XenForo.speed.fast).addClass("selected")});
a(".mediaContainer").hover(function(){a(this).find(".tagBox").xfFadeIn(XenForo.speed.fast)},function(){a(this).find(".tagBox").xfFadeOut(XenForo.speed.fast)})},showTags:function(){a(".TagBox").toggleClass("tagsShown")},updateMultiplier:function(){a(this.image).attr("data-scalewidth",this.image.width());a(this.image).attr("data-scaleheight",this.image.height());var h=a(this.image).attr("data-scalewidth")/a(this.image).attr("data-realwidth");a("#CropMultiplier").val(h);a("#TagMultiplier").val(h);a(".TagBox").each(function(d,
f){tagBox=a(f);tagBox.css({width:Math.round(tagBox.data("tagwidth")*h),height:Math.round(tagBox.data("tagheight")*h),top:Math.round(tagBox.data("tagtop")*h),left:Math.round(tagBox.data("tagleft")*h)});tagBoxInner=a(".TagBoxInner_"+tagBox.data("tagid"));tagBoxInner.css({width:Math.round(tagBox.data("tagwidth")*h)-6,height:Math.round(tagBox.data("tagheight")*h)-6});tagBoxName=a(".TagBoxName_"+tagBox.data("tagid"));tagBoxName.css({width:Math.round(tagBox.data("tagwidth")*h)})});a(".tagContainer").xfShow()}};
XenForo.register(".Image","XenForo.XenGalleryImageData")})(jQuery,this,document);
(function(a){XenForo.XenGalleryCrop=function(a){this.__construct(a)};XenForo.XenGalleryCrop.prototype={__construct:function(f){this.element=f;this.element.bind({click:a.context(this,"beginCrop")})},beginCrop:function(f){f.preventDefault();var f=a(f.target),n=f.closest(".Menu").data("XenForo.PopupMenu");n.hideMenu&&n.hideMenu(f,!0);if(XenForo.isTouchBrowser())return XenForo.alert(XenForo.phrases.xengallery_touch_error);this.element.addClass("primary");XenForo.alert(this.element.data("activatephrase"),
"info",1500,"");a("img.Tag").imgAreaSelect({disable:!0,hide:!0});a(".TagActivate").removeClass("primary");a("img.Crop").imgAreaSelect({disable:!1,handles:!0,aspectRatio:!1,maxWidth:!1,maxHeight:!1,fadeSpeed:200,onSelectEnd:function(h,d){a("#CropX1").val(d.x1);a("#CropY1").val(d.y1);a("#CropX2").val(d.x2);a("#CropY2").val(d.y2);a("#CropWidth").val(d.width);a("#CropHeight").val(d.height);this.queryString={media_id:a("#CropMediaId").val(),crop_x1:a("#CropX1").val(),crop_y1:a("#CropY1").val(),crop_x2:a("#CropX2").val(),
crop_y2:a("#CropY2").val(),crop_width:a("#CropWidth").val(),crop_height:a("#CropHeight").val(),crop_multiplier:a("#CropMultiplier").val()};if(d.width>0&&d.height>0)this.trigger={href:"index.php?xengallery/crop-confirm&"+a.param(this.queryString)},this.options={},this.OverlayLoader=new XenForo.OverlayLoader(a(this.trigger),!1,this.options),this.OverlayLoader.load()}})},endCrop:function(){a(".CropActivate").removeClass("primary");a("img.Crop").imgAreaSelect({disable:!0,hide:!0})}};XenForo.register(".CropActivate",
"XenForo.XenGalleryCrop")})(jQuery,this,document);
(function(a){XenForo.XenGalleryTag=function(a){this.__construct(a)};XenForo.XenGalleryTag.prototype={__construct:function(f){this.element=f;this.element.bind({click:a.context(this,"beginTag")})},beginTag:function(f){f.preventDefault();var f=a(f.target),n=f.closest(".Menu").data("XenForo.PopupMenu");n.hideMenu&&n.hideMenu(f,!0);if(XenForo.isTouchBrowser())return XenForo.alert(XenForo.phrases.xengallery_touch_error);this.element.addClass("primary");XenForo.alert(this.element.data("activatephrase"),
"info",1500,"");a("img.Crop").imgAreaSelect({disable:!0,hide:!0});a(".CropActivate").removeClass("primary");a("img.Tag").imgAreaSelect({disable:!1,handles:!0,aspectRatio:"1:1",maxWidth:200,maxHeight:200,fadeSpeed:200,onSelectEnd:function(h,d){a("#TagX1").val(d.x1);a("#TagY1").val(d.y1);a("#TagX2").val(d.x2);a("#TagY2").val(d.y2);a("#TagWidth").val(d.width);a("#TagHeight").val(d.height);this.queryString={media_id:a("#TagMediaId").val(),tag_x1:a("#TagX1").val(),tag_y1:a("#TagY1").val(),tag_x2:a("#TagX2").val(),
tag_y2:a("#TagY2").val(),tag_width:a("#TagWidth").val(),tag_height:a("#TagHeight").val(),tag_multiplier:a("#TagMultiplier").val()};if(d.width>0&&d.height>0)this.trigger={href:"index.php?xengallery/tag-input&"+a.param(this.queryString)},this.options={},this.OverlayLoader=new XenForo.OverlayLoader(a(this.trigger),!1,this.options),this.OverlayLoader.load()},onSelectStart:function(){a("#InlineTagOverlay").hide()}})},endTag:function(){a(".TagActivate").removeClass("primary");a("img.Tag").imgAreaSelect({disable:!0,
hide:!0})}};XenForo.register(".TagActivate","XenForo.XenGalleryTag")})(jQuery,this,document);
(function(a){function f(){return a("<div/>")}var n=Math.abs,h=Math.max,d=Math.min,k=Math.round;a.imgAreaSelect=function(x,c){var K,L;function M(a){return a+K-t.left}function N(a){return a+L-t.top}function F(a){return a-K+t.left}function G(a){return a-L+t.top}function A(a){var c=a||S,a=a||T;return{x1:k(b.x1*c),y1:k(b.y1*a),x2:k(b.x2*c),y2:k(b.y2*a),width:k(b.x2*c)-k(b.x1*c),height:k(b.y2*a)-k(b.y1*a)}}function fa(a,c,d,g,e){var h=e||S,e=e||T;b={x1:k(a/h||0),y1:k(c/e||0),x2:k(d/h||0),y2:k(g/e||0)};
b.width=b.x2-b.x1;b.height=b.y2-b.y1}function H(){Y&&u.width()&&(K=k(u.offset().left),L=k(u.offset().top),v=u.innerWidth(),s=u.innerHeight(),L+=u.outerHeight()-s>>1,K+=u.outerWidth()-v>>1,U=k(c.minWidth/S)||0,V=k(c.minHeight/T)||0,ga=k(d(c.maxWidth/S||16777216,v)),ha=k(d(c.maxHeight/T||16777216,s)),a().jquery=="1.3.2"&&Z=="fixed"&&!ia.getBoundingClientRect&&(L+=h(document.body.scrollTop,ia.scrollTop),K+=h(document.body.scrollLeft,ia.scrollLeft)),t=/absolute|relative/.test(O.css("position"))?{left:k(O.offset().left)-
O.scrollLeft(),top:k(O.offset().top)-O.scrollTop()}:Z=="fixed"?{left:a(document).scrollLeft(),top:a(document).scrollTop()}:{left:0,top:0},o=M(0),p=N(0),(b.x2>v||b.y2>s)&&$())}function aa(E){if(ba){l.css({left:M(b.x1),top:N(b.y1)}).add(P).width(B=b.width).height(I=b.height);P.add(r).add(q).css({left:0,top:0});r.width(h(B-r.outerWidth()+r.innerWidth(),0)).height(h(I-r.outerHeight()+r.innerHeight(),0));a(m[0]).css({left:o,top:p,width:b.x1,height:s});a(m[1]).css({left:o+b.x1,top:p,width:B,height:b.y1});
a(m[2]).css({left:o+b.x2,top:p,width:v-b.x2,height:s});a(m[3]).css({left:o+b.x1,top:p+b.y2,width:B,height:s-b.y2});B-=q.outerWidth();I-=q.outerHeight();switch(q.length){case 8:a(q[4]).css({left:B>>1}),a(q[5]).css({left:B,top:I>>1}),a(q[6]).css({left:B>>1,top:I}),a(q[7]).css({top:I>>1});case 4:q.slice(1,3).css({left:B}),q.slice(2,4).css({top:I})}if(E!==!1&&(a.imgAreaSelect.onKeyPress!=ra&&a(document).unbind(a.imgAreaSelect.keyPress,a.imgAreaSelect.onKeyPress),c.keys))a(document)[a.imgAreaSelect.keyPress](a.imgAreaSelect.onKeyPress=
ra);Q&&r.outerWidth()-r.innerWidth()==2&&(r.css("margin",0),setTimeout(function(){r.css("margin","auto")},0))}}function ja(a){H();aa(a);g=M(b.x1);e=N(b.y1);i=M(b.x2);j=N(b.y2)}function ka(a,b){c.fadeSpeed?a.fadeOut(c.fadeSpeed,b):a.hide()}function J(a){var e=F(a.pageX-t.left)-b.x1,a=G(a.pageY-t.top)-b.y1;la||(H(),la=!0,l.one("mouseout",function(){la=!1}));w="";c.resizable&&(a<=c.resizeMargin?w="n":a>=b.height-c.resizeMargin&&(w="s"),e<=c.resizeMargin?w+="w":e>=b.width-c.resizeMargin&&(w+="e"));l.css("cursor",
w?w+"-resize":c.movable?"move":"");ca&&ca.toggle()}function sa(){a("body").css("cursor","");(c.autoHide||b.width*b.height==0)&&ka(l.add(m),function(){a(this).hide()});a(document).unbind("mousemove",ma);l.mousemove(J);c.onSelectEnd(x,A())}function ta(E){if(E.which!=1)return!1;H();w?(a("body").css("cursor",w+"-resize"),g=M(b[/w/.test(w)?"x2":"x1"]),e=N(b[/n/.test(w)?"y2":"y1"]),a(document).mousemove(ma).one("mouseup",sa),l.unbind("mousemove",J)):c.movable?(na=o+b.x1-(E.pageX-t.left),oa=p+b.y1-(E.pageY-
t.top),l.unbind("mousemove",J),a(document).mousemove(ua).one("mouseup",function(){c.onSelectEnd(x,A());a(document).unbind("mousemove",ua);l.mousemove(J)})):u.mousedown(E);return!1}function W(a){C&&(a?(i=h(o,d(o+v,g+n(j-e)*C*(i>g||-1))),j=k(h(p,d(p+s,e+n(i-g)/C*(j>e||-1)))),i=k(i)):(j=h(p,d(p+s,e+n(i-g)/C*(j>e||-1))),i=k(h(o,d(o+v,g+n(j-e)*C*(i>g||-1)))),j=k(j)))}function $(){g=d(g,o+v);e=d(e,p+s);n(i-g)<U&&(i=g-U*(i<g||-1),i<o?g=o+U:i>o+v&&(g=o+v-U));n(j-e)<V&&(j=e-V*(j<e||-1),j<p?e=p+V:j>p+s&&(e=
p+s-V));i=h(o,d(i,o+v));j=h(p,d(j,p+s));W(n(i-g)<n(j-e)*C);n(i-g)>ga&&(i=g-ga*(i<g||-1),W());n(j-e)>ha&&(j=e-ha*(j<e||-1),W(!0));b={x1:F(d(g,i)),x2:F(h(g,i)),y1:G(d(e,j)),y2:G(h(e,j)),width:n(i-g),height:n(j-e)};aa();c.onSelectChange(x,A())}function ma(a){i=/w|e|^$/.test(w)||C?a.pageX-t.left:M(b.x2);j=/n|s|^$/.test(w)||C?a.pageY-t.top:N(b.y2);$();return!1}function X(E,d){i=(g=E)+b.width;j=(e=d)+b.height;a.extend(b,{x1:F(g),y1:G(e),x2:F(i),y2:G(j)});aa();c.onSelectChange(x,A())}function ua(a){g=h(o,
d(na+(a.pageX-t.left),o+v-b.width));e=h(p,d(oa+(a.pageY-t.top),p+s-b.height));X(g,e);a.preventDefault();return!1}function pa(){a(document).unbind("mousemove",pa);H();i=g;j=e;$();w="";m.is(":visible")||l.add(m).hide().fadeIn(c.fadeSpeed||0);ba=!0;a(document).unbind("mouseup",da).mousemove(ma).one("mouseup",sa);l.unbind("mousemove",J);c.onSelectStart(x,A())}function da(){a(document).unbind("mousemove",pa).unbind("mouseup",da);ka(l.add(m));fa(F(g),G(e),F(g),G(e));this instanceof a.imgAreaSelect||(c.onSelectChange(x,
A()),c.onSelectEnd(x,A()))}function va(c){if(c.which!=1||m.is(":animated"))return!1;H();na=g=c.pageX-t.left;oa=e=c.pageY-t.top;a(document).mousemove(pa).mouseup(da);return!1}function wa(){ja(!1)}function xa(){Y=!0;qa(c=a.extend({classPrefix:"imgareaselect",movable:!0,parent:"body",resizable:!0,resizeMargin:10,onInit:function(){},onSelectStart:function(){},onSelectChange:function(){},onSelectEnd:function(){}},c));l.add(m).css({visibility:""});c.show&&(ba=!0,H(),aa(),l.add(m).hide().fadeIn(c.fadeSpeed||
0));setTimeout(function(){c.onInit(x,A())},0)}function ea(a,b){for(var e in b)c[e]!==void 0&&a.css(b[e],c[e])}function qa(b){b.parent&&(O=a(b.parent)).append(l.add(m));a.extend(c,b);H();if(b.handles!=null){q.remove();q=a([]);for(R=b.handles?b.handles=="corners"?4:8:0;R--;)q=q.add(f());q.addClass(c.classPrefix+"-handle").css({position:"absolute",fontSize:0,zIndex:D+1||1});!parseInt(q.css("width"))>=0&&q.width(5).height(5);(z=c.borderWidth)&&q.css({borderWidth:z,borderStyle:"solid"});ea(q,{borderColor1:"border-color",
borderColor2:"background-color",borderOpacity:"opacity"})}S=c.imageWidth/v||1;T=c.imageHeight/s||1;if(b.x1!=null)fa(b.x1,b.y1,b.x2,b.y2),b.show=!b.hide;if(b.keys)c.keys=a.extend({shift:1,ctrl:"resize"},b.keys);m.addClass(c.classPrefix+"-outer");P.addClass(c.classPrefix+"-selection");for(R=0;R++<4;)a(r[R-1]).addClass(c.classPrefix+"-border"+R);ea(P,{selectionColor:"background-color",selectionOpacity:"opacity"});ea(r,{borderOpacity:"opacity",borderWidth:"border-width"});ea(m,{outerColor:"background-color",
outerOpacity:"opacity"});(z=c.borderColor1)&&a(r[0]).css({borderStyle:"solid",borderColor:z});(z=c.borderColor2)&&a(r[1]).css({borderStyle:"dashed",borderColor:z});l.append(P.add(r).add(ca)).append(q);Q&&((z=(m.css("filter")||"").match(/opacity=(\d+)/))&&m.css("opacity",z[1]/100),(z=(r.css("filter")||"").match(/opacity=(\d+)/))&&r.css("opacity",z[1]/100));b.hide?ka(l.add(m)):b.show&&Y&&(ba=!0,l.add(m).fadeIn(c.fadeSpeed||0),ja());C=(ya=(c.aspectRatio||"").split(/:/))[0]/ya[1];u.add(m).unbind("mousedown",
va);if(c.disable||c.enable===!1)l.unbind("mousemove",J).unbind("mousedown",ta),a(window).unbind("resize",wa);else{if(c.enable||c.disable===!1)(c.resizable||c.movable)&&l.mousemove(J).mousedown(ta),a(window).resize(wa);c.persistent||u.add(m).mousedown(va)}c.enable=c.disable=void 0}var u=a(x),Y,l=f(),P=f(),r=f().add(f()).add(f()).add(f()),m=f().add(f()).add(f()).add(f()),q=a([]),ca,o,p;K=0;L=0;var v,s,O,t={left:0,top:0},D=0,Z="absolute",na,oa,S,T,w,U,V,ga,ha,C,ba,g,e,i,j,b={x1:0,y1:0,x2:0,y2:0,width:0,
height:0},ia=document.documentElement,y=navigator.userAgent,ya,R,z,B,I,la,ra=function(a){var b=c.keys,f,k=a.keyCode;f=!isNaN(b.alt)&&(a.altKey||a.originalEvent.altKey)?b.alt:!isNaN(b.ctrl)&&a.ctrlKey?b.ctrl:!isNaN(b.shift)&&a.shiftKey?b.shift:!isNaN(b.arrows)?b.arrows:10;if(b.arrows=="resize"||b.shift=="resize"&&a.shiftKey||b.ctrl=="resize"&&a.ctrlKey||b.alt=="resize"&&(a.altKey||a.originalEvent.altKey)){switch(k){case 37:f=-f;case 39:a=h(g,i);g=d(g,i);i=h(a+f,g);W();break;case 38:f=-f;case 40:a=
h(e,j);e=d(e,j);j=h(a+f,e);W(!0);break;default:return}$()}else switch(g=d(g,i),e=d(e,j),k){case 37:X(h(g-f,o),e);break;case 38:X(g,h(e-f,p));break;case 39:X(g+d(f,v-F(i)),e);break;case 40:X(g,e+d(f,s-G(j)));break;default:return}return!1};this.remove=function(){qa({disable:!0});l.add(m).remove()};this.getOptions=function(){return c};this.setOptions=qa;this.getSelection=A;this.setSelection=fa;this.cancelSelection=da;this.update=ja;for(var Q=(/msie ([\w.]+)/i.exec(y)||[])[1],za=/opera/i.test(y),Aa=/webkit/i.test(y)&&
!/chrome/i.test(y),y=u;y.length;)D=h(D,!isNaN(y.css("z-index"))?y.css("z-index"):D),y.css("position")=="fixed"&&(Z="fixed"),y=y.parent(":not(body)");D=c.zIndex||D;Q&&u.attr("unselectable","on");a.imgAreaSelect.keyPress=Q||Aa?"keydown":"keypress";za&&(ca=f().css({width:"100%",height:"100%",position:"absolute",zIndex:D+2||2}));l.add(m).css({visibility:"hidden",position:Z,overflow:"hidden",zIndex:D||"0"});l.css({zIndex:D+2||2});P.add(r).css({position:"absolute",fontSize:0});x.complete||x.readyState==
"complete"||!u.is("img")?xa():u.one("load",xa);if(!Y&&Q&&Q>=7)x.src=x.src};a.fn.imgAreaSelect=function(d){d=d||{};this.each(function(){if(a(this).data("imgAreaSelect"))d.remove?(a(this).data("imgAreaSelect").remove(),a(this).removeData("imgAreaSelect")):a(this).data("imgAreaSelect").setOptions(d);else if(!d.remove){if(d.enable===void 0&&d.disable===void 0)d.enable=!0;a(this).data("imgAreaSelect",new a.imgAreaSelect(this,d))}});return d.instance?a(this).data("imgAreaSelect"):this}})(jQuery);
