/*
 * XenForo media_comments.min.js
 * Copyright 2010-2016 XenForo Ltd.
 * Released under the XenForo License Agreement: http://xenforo.com/license-agreement
 */
(function(d,g,f){XenForo.XenGalleryMedia={Comment:function(c){c.bind("AutoValidationComplete",function(b){b.ajaxData.templateHtml&&(b.preventDefault(),d("#MediaNoComments").slideUp(XenForo.speed.fast,function(){new XenForo.ExtLoader(b.ajaxData,function(){d(b.ajaxData.templateHtml).xfInsert("appendTo","#MediaNewComments")});d(".MediaComment").find("textarea").val("");var a=d("#CommentForm").find("textarea");a.val("");(a=a.data("XenForo.BbCodeWysiwygEditor"))&&a.resetEditor();c.find("input[name=date]").val(b.ajaxData.date);
c.find("input:submit").removeAttr("disabled").removeClass("disabled")}))})},InlineComment:function(c){c.bind("AutoValidationComplete",function(b){var a=c.closest("div.xenOverlay").data("overlay");a&&a.getTrigger().data("target");b.ajaxData.templateHtml&&(b.preventDefault(),a&&a.close().getTrigger().data("XenForo.OverlayTrigger").deCache(),new XenForo.ExtLoader(b.ajaxData,function(){var a=b.ajaxData.commentId;a&&d(b.ajaxData.templateHtml).xfInsert("replaceAll","#comment-"+a,"xfShow")}),d(".MediaComment").find("textarea").val(""),
c.find("input[name=date]").val(b.ajaxData.date),c.find("input:submit").removeAttr("disabled").removeClass("disabled"))})},ShowComment:function(c){c.click(function(b){b.preventDefault();var a=c.data("commentid");a&&XenForo.ajax(c.attr("href"),{},function(b){d("#comment-"+a).xfFadeUp();d(b.templateHtml).xfInsert("insertAfter","#comment-"+a).xfFadeDown()})})},CreateReply:function(c){c.click(function(b){b.preventDefault();var a=c.data("username"),b=d("#CommentForm");if(a){var e=XenForo.getEditorInForm(b),
a="@"+a+" ";if(!e)return!1;d(f).scrollTop(b.offset().top);e.$editor?(e.focus(!0),e.insertHtml(XenForo.htmlspecialchars(a)),e.$editor.data("xenForoElastic")&&e.$editor.data("xenForoElastic")()):(e.focus(),e.val(e.val()+a))}})}};XenForo.register("form.MediaComment","XenForo.XenGalleryMedia.Comment");XenForo.register("form.MediaInlineComment","XenForo.XenGalleryMedia.InlineComment");XenForo.register("a.MediaShowComment","XenForo.XenGalleryMedia.ShowComment");XenForo.register("a.ReplyLink","XenForo.XenGalleryMedia.CreateReply")})(jQuery,
this,document);
